---
- hosts: all
  user: ubuntu
  become: yes
  gather_facts: True
  tasks:
  - set_fact:
      interface_path: "/etc/network/interfaces"
      new_interface_path: "/etc/network/interfaces.bck"
      eno1_addr: ansible_eno1.ipv4.address
      br0_addr: ansible_br0.ipv4.address

  - name: Backup interfaces file
    command: mv "{{ interface_path }}" "{{ interface_path }}".bck
  - name: Create a new file
    file:
      path: "{{ interface_path }}"
      state: touch
      mode: 0644
      owner: root
      group: root

  - name: new interfaces file
    blockinfile:
      mode: 0644
      path: "{{ interface_path }}"
      state: present
      block: |
        auto lo
        iface lo inet loopback
          dns-search maas
          dns-nameservers 10.245.0.10

        auto eno1
        iface eno1 inet static
           dns-nameservers 10.245.0.10
           address {{ ansible_eno1.ipv4.address }}
           netmask 255.255.255.0

        auto eno2
        auto br0
        iface br0 inet static
           pre-up ip link add veno0 type veth peer name veno1
           pre-up ifconfig veno0 up
           pre-up ifconfig veno1 up
           bridge_ports eno2 veno0
           bridge_fd 0
           bridge_maxwait 0
           address {{ ansible_br0.ipv4.address }}
           netmask 255.255.255.0
           gateway 10.245.122.253
           up route add -net 10.245.122.0 netmask 255.255.255.0 gw 10.245.122.253 br0

  - name: Restart server
    command: shutdown -r now "Reboot triggered by Ansible"
    async: 0
    poll: 0
    ignore_errors: true

  - name: Wait for server to restart
    local_action:
      module: wait_for
        host={{ inventory_hostname }}
        port=22
        delay=1
        timeout=300
