---
- name: oneTime
  hosts: all
  become: yes
  tasks:
    - include: tasks/Install.yml
  tags: oneTime

- name: Generate Interfaces (Create Public interface)
  hosts: all
  vars:
    network_Oct: "0"
    gateway_Oct: "253"
    DNS_NAMESERVER: "129.115.103.72"
  vars_prompt:
    - name: "CIDR"
      prompt: "What is the first 3 octets of the IP? i.e. 10.245.122."
      default: "10.245.122."
      private: no
  tasks:
    - include: tasks/Generate_interfaces.yml
  tags: generate_public_interfaces

- name: Remove public interfaces
  hosts: 'all:!control:!monitoring:!network'
  vars:
    network_Oct: "0"
    gateway_Oct: "253"
    DNS_NAMESERVER: "129.115.103.72"
  tasks:
    - include: tasks/Destroy_interfaces.yml
  tags: destroy_public_interfaces

- name: Refresh the ceph partitions
  hosts: storage
  tasks:
    - include: tasks/ceph.yml
  tags: ceph

- name: Delete all VM's from cluster
  hosts: compute
  tasks: 
    - include: tasks/delete_docker_images_and_VMs.yml
  tags: kill_VMs

- name: Reboot all nodes
  hosts: all
  tasks:
    - include: tasks/Reboot.yml
  tags: Reboot
