- name: Delete local docker images
  shell: docker rmi -f $(docker images --quiet)
  become: yes
  ignore_errors: true

- name: Kill all running VM's
  shell: kill `ps aux | grep -F 'qemu' | awk '{ print $2 }'`
  become: yes
  ignore_errors: true
