---
- name: Ubuntu - Uninstall LXD and LXC
  become: yes
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - lxd
    - lxc
  when: ansible_distribution == 'Ubuntu'

- name: CentOS - Uninstall LXD and LXC
  become: yes
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - lxd
    - lxc
  when: ansible_distribution == 'CentOS'

- name: Make sure internal IPv4 and hostname is in etc/hosts
  lineinfile:
      line: "{{ ansible_eno1.ipv4.address }} {{ inventory_hostname }}"
      path: /etc/hosts
      state: present
      owner: root
      group: root
      mode: 0644
  become: yes
  async: 60
  poll: 5


- name: Allow root to SSH
  command: cp /home/ubuntu/.ssh/authorized_keys /root/.ssh/authorized_keys
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: CentOS - Allow root to SSH
  command: cp /home/centos/.ssh/authorized_keys /root/.ssh/authorized_keys
  become: yes
  when: ansible_distribution == 'CentOS'
