---
- name: Restart server
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  become: yes
  ignore_errors: true

- name: Wait for server to restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      state=started
      port=22
      delay=1
      timeout=600
      connect_timeout=15
